on:
  release:
    types: [published]
jobs:
  generate_changelog:
    runs-on: ubuntu-latest # Configure this based on your needs
    name: Update Changelog
    steps:
      - name: Create Changelog.md
        id: changelog
        uses: nextrelease/changelog-generator-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Required
          changelog: 'CHANGELOG.md' # optional, default: CHANGELOG.md
